# 03_limpieza_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.

# Obtención de los datos epidemiológicos

In [2]:
# Inicio del análisis
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Adicionar al dataset los atributos meteorológicos rezagados con un rezago hasta de 12 semanas.

In [3]:
ubicacion_datos = r"C:\Users\marco\Documentos\investigacion\arima\2_ejecucion_plan_trabajo\03_fusionar_generar_rezagos\2_generar_rezagos\2_datos\1_raw\datos_semanal_meteo_completos_epi_sin_rezagos.xlsx"
df_semanal_meteo_epi= pd.read_excel(ubicacion_datos)
df_semanal_meteo_epi.head()

,fecha,año,semana_epi,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,vel_vi,vel_vi_max,vel_vi_min,uv,soi,sst,casos_dengue
0,2021-01-03,2021,1,28.254286,34.200000,23.832857,16.367143,70.774286,7.73,1,0.124286,0.268571,0.047143,2.222857,20.067143,-1.060214,0
1,2021-01-10,2021,2,28.638571,34.910000,24.195714,17.318571,73.095714,19.18,5,0.111429,0.204286,0.038571,2.254286,18.207143,-1.058352,0
2,2021-01-17,2021,3,29.552857,36.372857,24.090000,16.122857,65.328571,0.80,0,0.122857,0.227143,0.045714,2.420000,10.847143,-0.931407,1
3,2021-01-24,2021,4,29.208571,35.978571,24.200000,16.564286,68.205714,12.81,5,0.122857,0.220000,0.035714,2.477143,15.430000,-0.837360,0
4,2021-01-31,2021,5,29.421429,35.882857,24.684286,17.311429,69.797143,18.06,3,0.117143,0.225714,0.030000,2.290000,9.348571,-0.897892,0

In [4]:
# Lista de variables meteorológicas
variables_locales = ['temp', 'temp_max', 'temp_min',
       'hum_esp', 'hum_rel', 'prec', 'dias_lluvia', 'vel_vi', 'vel_vi_max',
       'vel_vi_min', 'uv'
]

variables_macroclimaticas = ['soi', 'sst']

# Número de rezagos para las variables locales y macroclimáticas
max_lag_local = 8

# Definimos el inicio y fin de los rezagos macroclimáticos (de 8 a 12)
min_lag_macro = 8
max_lag_macro = 12

# Iniciar el DataFrame de rezagos a partir del original
df_semanal_meteo_epi_rezagos = df_semanal_meteo_epi.copy()

# Generar rezagos para variables locales (del lag 1 al 8)
for var in variables_locales:
    for lag in range(1, max_lag_local + 1):
        df_semanal_meteo_epi_rezagos[f"{var}_lag_{lag}"] = df_semanal_meteo_epi_rezagos[var].shift(lag)

# Generar rezagos para variables macroclimáticas (del lag 8 al 12)
for var in variables_macroclimaticas:
    for lag in range(min_lag_macro, max_lag_macro + 1):
        df_semanal_meteo_epi_rezagos[f"{var}_lag_{lag}"] = df_semanal_meteo_epi_rezagos[var].shift(lag)

# Ver resultado
df_semanal_meteo_epi_rezagos.head(15)

C:\Users\marco\AppData\Local\Temp\ipykernel_23016\475162913.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_semanal_meteo_epi_rezagos[f"{var}_lag_{lag}"] = df_semanal_meteo_epi_rezagos[var].shift(lag)

,fecha,año,semana_epi,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,...,soi_lag_8,soi_lag_9,soi_lag_10,soi_lag_11,soi_lag_12,sst_lag_8,sst_lag_9,sst_lag_10,sst_lag_11,sst_lag_12
0,2021-01-03,2021,1,28.254286,34.200000,23.832857,16.367143,70.774286,7.73,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-10,2021,2,28.638571,34.910000,24.195714,17.318571,73.095714,19.18,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-17,2021,3,29.552857,36.372857,24.090000,16.122857,65.328571,0.80,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-24,2021,4,29.208571,35.978571,24.200000,16.564286,68.205714,12.81,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-31,2021,5,29.421429,35.882857,24.684286,17.311429,69.797143,18.06,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-02-07,2021,6,29.980000,36.214286,25.011429,16.530000,64.671429,11.59,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-02-14,2021,7,28.827143,35.214286,24.310000,16.551429,69.462857,14.29,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-02-21,2021,8,30.384286,37.588571,24.681429,16.070000,62.417143,2.15,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-02-28,2021,9,29.235714,35.844286,23.867143,15.074286,62.458571,9.82,2,...,20.067143,NaN,NaN,NaN,NaN,-1.060214,NaN,NaN,NaN,NaN
9,2021-03-07,2021,10,28.814286,34.601429,24.411429,15.761429,65.838571,0.13,0,...,18.207143,20.067143,NaN,NaN,NaN,-1.058352,-1.060214,NaN,NaN,NaN
10,2021-03-14,2021,11,28.874286,33.964286,24.854286,15.995714,65.982857,0.92,0,...,10.847143,18.207143,20.067143,NaN,NaN,-0.931407,-1.058352,-1.060214,NaN,NaN
11,2021-03-21,2021,12,29.614286,35.315714,25.154286,15.391429,61.167143,0.17,0,...,15.430000,10.847143,18.207143,20.067143,NaN,-0.837360,-0.931407,-1.058352,-1.060214,NaN
12,2021-03-28,2021,13,31.554286,36.747143,26.918571,15.725714,55.717143,0.67,0,...,9.348571,15.430000,10.847143,18.207143,20.067143,-0.897892,-0.837360,-0.931407,-1.058352,-1.060214
13,2021-04-04,2021,14,29.200000,33.907143,25.458571,16.550000,66.907143,5.02,2,...,16.120000,9.348571,15.430000,10.847143,18.207143,-0.977896,-0.897892,-0.837360,-0.931407,-1.058352
14,2021-04-11,2021,15,28.248571,32.278571,25.132857,17.790000,75.144286,40.07,5,...,18.705714,16.120000,9.348571,15.430000,10.847143,-0.803088,-0.977896,-0.897892,-0.837360,-0.931407

In [5]:
df_semanal_meteo_epi_rezagos.columns    
df_semanal_meteo_epi_rezagos.tail(5)

,fecha,año,semana_epi,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,...,soi_lag_8,soi_lag_9,soi_lag_10,soi_lag_11,soi_lag_12,sst_lag_8,sst_lag_9,sst_lag_10,sst_lag_11,sst_lag_12
256,2025-11-30,2025,49,25.527143,28.834286,23.218571,18.514286,90.482857,27.53,6,...,12.264286,1.620000,2.591429,-0.221429,-4.208571,-0.268223,-0.346037,-0.454914,-0.329364,-0.353051
257,2025-12-07,2025,50,26.065714,29.091429,23.882857,19.224286,90.717143,21.56,4,...,2.555714,12.264286,1.620000,2.591429,-0.221429,-0.366160,-0.268223,-0.346037,-0.454914,-0.329364
258,2025-12-14,2025,51,26.038571,29.442857,23.658571,18.982857,89.951429,30.71,6,...,16.565714,2.555714,12.264286,1.620000,2.591429,-0.436933,-0.366160,-0.268223,-0.346037,-0.454914
259,2025-12-21,2025,52,25.997143,30.090000,23.008571,17.992857,85.818571,2.49,1,...,17.272857,16.565714,2.555714,12.264286,1.620000,-0.461052,-0.436933,-0.366160,-0.268223,-0.346037
260,2025-12-28,2025,53,26.078571,29.490000,23.778571,19.051429,90.030000,14.34,3,...,22.954286,17.272857,16.565714,2.555714,12.264286,-0.460149,-0.461052,-0.436933,-0.366160,-0.268223

In [6]:
# Eliminar filas con valores NaN (debido a los rezagos)
df_semanal_meteo_epi_rezagos = df_semanal_meteo_epi_rezagos.dropna().reset_index(drop=True) 
df_semanal_meteo_epi_rezagos.head(5)

,fecha,año,semana_epi,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,...,soi_lag_8,soi_lag_9,soi_lag_10,soi_lag_11,soi_lag_12,sst_lag_8,sst_lag_9,sst_lag_10,sst_lag_11,sst_lag_12
0,2021-03-28,2021,13,31.554286,36.747143,26.918571,15.725714,55.717143,0.67,0,...,9.348571,15.430000,10.847143,18.207143,20.067143,-0.897892,-0.837360,-0.931407,-1.058352,-1.060214
1,2021-04-04,2021,14,29.200000,33.907143,25.458571,16.550000,66.907143,5.02,2,...,16.120000,9.348571,15.430000,10.847143,18.207143,-0.977896,-0.897892,-0.837360,-0.931407,-1.058352
2,2021-04-11,2021,15,28.248571,32.278571,25.132857,17.790000,75.144286,40.07,5,...,18.705714,16.120000,9.348571,15.430000,10.847143,-0.803088,-0.977896,-0.897892,-0.837360,-0.931407
3,2021-04-18,2021,16,29.072857,34.704286,25.035714,17.598571,72.110000,22.25,1,...,2.744286,18.705714,16.120000,9.348571,15.430000,-1.097763,-0.803088,-0.977896,-0.897892,-0.837360
4,2021-04-25,2021,17,29.080000,34.357143,25.041429,16.558571,67.494286,1.46,1,...,-6.417143,2.744286,18.705714,16.120000,9.348571,-0.838514,-1.097763,-0.803088,-0.977896,-0.897892

In [8]:
# Guardar el DataFrame con rezagos
df_semanal_meteo_epi_rezagos = df_semanal_meteo_epi_rezagos.dropna().reset_index(drop=True) 
df_semanal_meteo_epi_rezagos.to_excel(r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\datos_consolidados\1_datos_semana_epi_meteo\datos_semanal_meteo_epi_con_rezagos\datos_semanal_meteo_epi_con_rezagos.xlsx", index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\datos_consolidados\1_datos_semana_epi_meteo\datos_semanal_meteo_epi_con_rezagos'

In [9]:
# Guardar el DataFrame con rezagos
df_semanal_meteo_epi_rezagos = df_semanal_meteo_epi_rezagos.dropna().reset_index(drop=True) 
ubicacion_con_rezagos = r"C:\Users\marco\Documentos\investigacion\arima\2_ejecucion_plan_trabajo\03_fusionar_generar_rezagos\2_generar_rezagos\2_datos\2_procesados_rezagos\datos_meteo_completos_epi_con_rezagos.xlsx"
df_semanal_meteo_epi_rezagos.to_excel(ubicacion_con_rezagos, index=False)

Tarea de resumir esta limpieza, **remuestreo** y fusion de datos, en una sola diapositiva.