# 02 Recoleccion_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.


# 2. Recolección de datos. 
     - Contar la historia con los datos. 

1. Decribir el origen de los datos:
   * meteorológicos: Describir el proceso y dificultades de obtención de fuentes. 
   * epidemiológicos: Descibir el proceso de estructuración de los datos.  
2. Contar el aspecto técnico de obtención de datos: Que utilizón Open Source. Que se utilizó la librería Pandas de Python (Wes Mckiney) y la estructura de datso utilizada fue DataFrame.


Los datos epidemiológicos utilizados en este estudio fueron obtenidos a partir de la base de datos suministrada por la Secretaría de Salud del municipio de Caucasia, Antioquia, la cual contiene los registros de casos notificados de dengue.

Por otra parte, los datos climáticos fueron obtenidos de la plataforma NASA POWER, una fuente de acceso abierto que proporciona información meteorológica con cobertura temporal continua.

El periodo de estudio comprendió los años 2021 a 2025, seleccionado con el fin de analizar el comportamiento reciente de los casos de dengue y su posible relación con las variables climáticas en el municipio de Caucasia.


2. Describir las variables y fundamentar su elección. 
   * meteorológicos
   * epidemiológicos.

## 2.1 Datos epidemiológicos

* Casos por fecha
* Municipio
* Semana epidemiológica

Para la estimación del número de casos de dengue por semana epidemiológica, se utilizaron variables específicas provenientes de la base de datos suministrada por la Secretaría de Salud. En particular, se empleó la variable fecha de inicio de síntomas, la cual permitió ubicar temporalmente cada caso y realizar su posterior agregación semanal. Asimismo, se filtraron los registros según el municipio de procedencia, seleccionando únicamente los casos correspondientes a Caucasia, Antioquia.


Adicionalmente, se consideraron las variables de ubicación como barrio y vereda, con el fin de describir la distribución espacial de los casos dentro del municipio. Cabe resaltar que los datos originales se encontraban reportados como casos ocurridos en fechas específicas, por lo que fue necesario realizar una transformación temporal.


Este proceso se llevó a cabo mediante el uso de Python, donde las fechas de inicio de síntomas fueron convertidas a semanas epidemiológicas siguiendo los lineamientos establecidos por el Instituto Nacional de Salud (INS) de Colombia. Esto permitió estandarizar la información y obtener el número de casos agregados por semana, incluyendo aquellas semanas en las que no se presentaron casos, garantizando así la continuidad de la serie temporal.


En cuanto a las variables meteorológicas, estas fueron obtenidas a partir de la plataforma NASA POWER, de donde se extrajeron datos correspondientes a temperatura (promedio, máxima y mínima), precipitación, humedad (relativa y específica) y velocidad del viento (promedio, máxima y mínima). La selección de estas variables se fundamenta en su influencia sobre la dinámica del vector Aedes aegypti, particularmente en aspectos como su desarrollo, supervivencia y capacidad de dispersión.


A partir de la variable de precipitación, se derivó una variable adicional correspondiente al número de días con lluvia, definida como aquellos días con valores iguales o superiores a 1 mm de precipitación. Esta variable fue incluida debido a su relevancia en la formación de criaderos del vector, lo cual puede incidir en el incremento del riesgo de transmisión del dengue.

# Obtención de los datos epidemiológicos estructurados por Janis e Idalina

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
# Importar datos epidemiológicos 
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Secretaria de salud\BD_DENGUE_2021-2025.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\3_datos_version_6_abril_2026\epidemiologicos.xlsx"
df_epi=pd.read_excel(ubicacion_marco)
df_epi.head(2)

,ini_sin_,semana,año,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,nmun_proce,nmun_resi
0,2021-01-21,3,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CR 39 E 48 C SUR 36,CAUCASIA,ENVIGADO
1,2021-02-08,6,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CL 29 A 42-99,CAUCASIA,BOGOTA

# Selección de los atributos epidemológicos que se considerarán en la investigación

1. Fecha  en que se iniciaron los síntomas de dengue (ini_sin)
2. Año (año)
3. Barrios (bar_ver)
4. Municipio de procedencia (nmun_proce) para este análisis es Caucasia


## 2.2 Datos meteorológicos

Fuentes posibles:

* NASA POWER

# Obtención de los datos meteorológicos o variables exógenas.

In [2]:
import pandas as pd 
# Importar datos meteorológicos 
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos meteorológicos\Datos_NS_2021-2025.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\3_datos_version_6_abril_2026\meteorologicos.xlsx"
df_meteo=pd.read_excel(ubicacion_marco)
df_meteo.head(2)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,QV2M,RH2M,PRECTOTCORR,WS2M,WS2M_MAX,WS2M_MIN,ALLSKY_SFC_UV_INDEX,SOI,SST_ANOMALY
0,2021,3,28.33,35.09,23.84,18.15,78.13,5.83,0.13,0.32,0.07,2.48,23.42,-1.038442
1,2021,4,28.71,35.05,23.69,16.29,69.26,0.77,0.14,0.30,0.07,2.47,25.40,-1.071886

# Selección de los atributos

Variables típicas:

* Temperatura
* Precipitación
* Humedad relativa
* Humedad específica 
* UV
* Velocidad del viento

# Tarea

Describa la secuencia de de pasos que realizó para obtener los atributos meteorlógicos nuevos SOI y SST: 
  - La razón teórica de haberlos considerado para su invetigación: (Incluir los referentes que lo sustentan: Para explicar el comportamiento decreciente de casos_dengue de 2025)
  - Lugar de de donde los obtuvo (Coloca la URL de donde bajó los datos)
  - Contar el formato, tipo de archivo y tamaño de los datos nuevo obtenidos. 
  - Entregar el script de Python para fusionar estos nuevos datos con los datos meteorológicos qye ya tenía.

# Ejecución de tarea  

Describa la de haberlos considerado para su invetigación: (Incluir los referentes que lo sustentan: Para explicar el comportamiento decreciente de casos_dengue de 2025)
  - Lugar de de donde los obtuvo (Coloca la URL de donde bajó los datos)
  - Contar el foa secuencia de de pasos que realizó para obtener los atributos meteorlógicos nuevos SOI y SST: 
  - La razón teóricrmato, tipo de archivo y tamaño de los datos nuevo obtenidos.
  -

In [11]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\marco\Downloads\soi.txt", sep ='\t') 
df.head()

   Year Day  Tahiti  Darwin     SOI
0  1991 157 1010.74 1010.90  -10.21
1  1991 158 1011.85 1011.40   -5.91
2  1991 159 1012.56 1011.80   -3.71
3  1991 160 1011.35 1012.40  -16.45
4  1991 161 1011.14 1013.25  -23.92

 
  - Entregar el script de Python para fusionar estos nuevos datos con los datos meteorológicos qye ya tenía.

# Resumir en una diapositiva la recolección de datos.